### ISSUE TITLE
Creating A List

### ISSUE THREAD

**Issue by nathanpuls** [denno020/linkslist#14]
Hey Luke,

It says lists can only be created while logged in. I was logged and and wasn't able to create a list in that state either.

Also when trying to click in the bottom right to learn more about you it just has the PayPal donation link. Not sure if that's intended.

Thanks! Cool project also.
Nathan

**Comment by denno020** [comment]
Gday Nathan!

Thanks for reaching out. I don't believe it says anywhere that lists can only be created by people who are logged in, are you able to point me directly to where it says that? As that is wrong, you definitely don't _have_ to be logged in to create a list.
Creating a list while logged in does have benefits though, like that list being associated with you as the author, which will allow for marking the list as private/read only in the future (I'm currently working on that feature).

Are you able to tell me which feature is breaking that is preventing you from creating a list? E.g. are you not able to add links? Or does the `Get Link` button not work?

As for the PayPal donation link, that is intentional. It's a way that people can bring that popup back up if they're previously dismissed in, in case they've found value in the app.

Thanks again
Luke

**Comment by nathanpuls** [comment]
In WELCOME BACK > My Lists > My Lists
Please note, only lists created while you're logged in will be displayed here
You have not yet created any lists

(it says that while I'm logged in)

**Comment by nathanpuls** [comment]
I was looking to add multiple lists

**Comment by denno020** [comment]
Ah yes, that is correct. That's indicating that only lists created while logged in will be able to be associated with you (which allows for those features mentioned). So it doesn't say that only logged in users can create a list

Have you created any lists yet? If the confusion is around being able to create a second list, that is a UI addition that I need to make, as isn't super clear, but you can just go to [linkslist.app/app](https://linkslist.app/app) again, and it will start you off with a new list (unless you've got a draft list that hasn't yet been saved to the DB, that will be recovered from local storage)

**Comment by nathanpuls** [comment]
Thanks for clarifying.
I’d love to be able to make lots of link lists.

I have a service where I connect people with their own link. Fwdng.com.

I want to basically give people their own url at fwdng and then connect
them to services like yours if they want the ability to have lots of links
rather than just one.

What web stack did you use to make your site?

**Comment by denno020** [comment]
The frontend is build using Vue, and the backend is run on Firebase.

I'm going to go ahead and close this issue now, as I believe we have resolved it. Please let me know if you have any other issues though
