### ISSUE TITLE
Notion links do not work

### ISSUE THREAD

**Issue by Gatienzo** [denno020/linkslist#26]
https://forcingfunction.notion.site/Forcing-Function-Performance-Library-8b594e8ee24e41048b1564a14f403039
gets converted to
notion.so

Also some previews fail e.g.
https://www.mayoclinic.org/es-es/diseases-conditions/schizotypal-personality-disorder/symptoms-causes/syc-20353919

**Comment by denno020** [comment]
Hey @Gatienzo,

Thanks for reporting! The way the link scraping works is rather basic, it sends a HTTP request to the website and scrapes the meta data (data that is read by Google/Facebook etc when indexing/sharing). In this instance, I believe the Notion page is built client side, which means when Links List makes the request server side, the JavaScript that is needed to populate the page doesn't get run, so we only get the most basic of information back. This is going to be an issue for all Single Page Apps that are rendered exclusively client side.

This is a limitation that I'm aware of, and I'm currently looking into more premium ways of previewing websites, so that we can actually scrap meta data from these client-side only websites

**Comment by Gatienzo** [comment]
ok thanks for the explanation
