### ISSUE TITLE
Feature Request: Lock list modification

### ISSUE THREAD

**Issue by dgriff03** [denno020/linkslist#5]
Thank you for this wonderful project! 

Would it be reasonable to add a bit to that enables "locking" in the "listsRef" and in the "exports.syncData" firebase function that rejects any changes if "locked" is set.

I'd love to share out the a list of links widely but it would be nice to know that someone malicious couldn't edit the the list if they wanted.

**Comment by denno020** [comment]
Hey @dgriff03, thanks for the feature request!

This is one of the first things that I want to add in a new round of features, but I'm going to have to add it to a premium version of Links List, as at that point Links List will need to start managing log in credentials.

We could certainly add the ability to lock a list so that it could never change, but I worry that might leave Links List open to have hundreds of abandoned lists (e.g. in the case that someone wants to add something new to a list they've locked, but as it's locked, they have to created a new, near identical list).

If you want to be notified when new features are pushed, be sure to enter your email into the Subscribe field on the websites homepage - or register your interest for a pro version, both will be notified of new features :)

**Comment by dgriff03** [comment]
Gotcha, that makes sense around wanting to avoid the build-up of abandoned lists and otherwise need to have the authentication around it.

Thanks for the quick response!
