### ISSUE TITLE
Preview linkslist.app

### ISSUE THREAD

**Issue by paulmwatson** [denno020/linkslist#6]
Firstly, what a great service, thank you.

I created a personal "Home" list and then "Todo" and "To Read" lists and wanted to add them to my "Home" list. It works but there is no preview for linkslist.app links.

**Comment by denno020** [comment]
Hi @paulmwatson,

Thank you for your kind words! I'm glad you're finding use with Links List.

This is a new way of using it! Links List inception, I love it :P. Unfortunately, the way that Links List is set up means that it doesn't lend itself to being added to one of its own lists. I'll explain:

Links List is set up as a Single Page Application (SPA). This means there aren't any servers involved in serving up the content for each list that people create. In order for Links List to be able to parse information of a link that is added, there needs to be a server that will provide that information.
Essentially it's the same issue that author's of SPA's face when it comes to Search Engine Optimization (SEO).
In Links List's case, I actually prefer that Google and others have trouble parsing the URL (and I've explicitly told them not to), because I don't want people inadvertently having their information shared. The lists are public, but I would like to try and keep them only as public as the author wants to make them.
In saying that, I've edited your comment to remove the screenshot. The image had your list ID's, and because all lists are public, it means anyone could visit those links and add/remove, so I'm hoping to prevent that.

Please let me know if you have any other questions!

**Comment by paulmwatson** [comment]
Thanks for responding Luke, understood and closing this issue.
